### PR TITLE
[WIP] Initial AlphaAnimals Support

### PR DESCRIPTION
**Pull request by WasmachenDennSachenSo**
Jo, Vegapnk. Hey, Shabalox 

I've started working on initial support for AlphaAnimals. I wanted to create this pull request to get some feedback on on the layout I've created and to be sure I didn't make a major mistake by now :) I don't want this to be merged just jet.

You guys have to know, I'm new to all this and I don't want to fuck It up.
So please be gentle with me and tell me if i do something wrong (which I will).

Note: Some GeneDefs are not complete and were just for testing purpose.

Progress:
- [ ] AcanthamoebaGigantea
- [x] AeroFleet
- [ ] Agaripawn/pod
- [ ] AngelMoth
- [x] AnimaColossus
- [ ] Animalisk
- [ ] AnimusVox
- [x] ArcticLion
- [x] Atispec
- [x] AuroraSlyph
- [ ] BarbSlinger
- [x] BedBug
- [x] Behemoth
- [x] BlackHive
- [ ] Blizzarisk
- [ ] BloodShrimp
- [ ] Bobeene
- [x] BoulderMit
- [ ] Bumbledrone
- [x] Cactipine
- [ ] ChameleonYak
- [ ] ChemfuelMyrmidon
- [ ] Cinderlisk
- [ ] CrepuscularBeetle
- [ ] CescendoAnole
- [x] CrystalMit
- [x] CrystallineCaracal
- [x] DarkVandal
- [x] Darkbeast
- [ ] DecayDrake
- [ ] DesertAve
- [x] DevilSheep
- [ ] Drainer
- [ ] Dunealisk
- [x] DuskPowler
- [ ] Duskrat
- [ ] EmpressButterfly
- [ ] EngorgedTentacularAberration
- [ ] Erin
- [ ] Eyeling
- [ ] Feralisk
- [ ] FireWasp
- [x] FissionMouse
- [ ] FlamingoPhoenix
- [ ] FrostAve
- [x] FrostLynx
- [x] FristMite
- [ ] FrostHoundBehemoth
- [ ] Frostling
- [ ] FungalHusk
- [ ] Gallatross
- [x] Genix
- [ ] GiantCrownedSilkie
- [ ] Gigantelope
- [x] GreatDevourer
- [ ] GreenGoo
- [ ] GreyCoatedMouflon
- [ ] GroundRunner
- [x] Helixien
- [ ] InfectedAerofleet
- [ ] IronHuskBeetle
- [ ] Junglelisk
- [ ] Lockjaw
- [ ] LuciferBug
- [x] MammothWorm
- [x] Mantrap
- [ ] MatureFleshBeast
- [ ] MeadowAve
- [x] MegaLouse
- [ ] Metallovore
- [ ] Mime
- [x] Murkling
- [ ] MycoidColossus
- [ ] NeedlePost
- [ ] NeedleRoll
- [ ] NightMule
- [ ] NightAve
- [ ] Nightling
- [ ] Nightram
- [ ] OcularJelly
- [ ] OcularNightling
- [ ] OvergrownColossus
- [ ] PebbleMit
- [ ] PedigreedRaptor
- [ ] PhoenixOwlcat
- [ ] Plasmorth
- [ ] Radyak
- [ ] RaptorShrimp
- [ ] Ravager
- [ ] RayHound
- [ ] Razorjack
- [ ] RedGoo
- [ ] RedSpore
- [ ] RiperHound
- [ ] RoughPlatedMonitor
- [ ] RoyalAve
- [ ] SandLion
- [ ] SandProwler
- [x] SandSquid
- [x] ShadowCharger
- [ ] ShockGoat
- [ ] Skiphound
- [x] ArcturanSkyEel
- [ ] Slurrypede
- [ ] Swarmling
- [ ] SpinedGow
- [ ] TarGuzzler
- [ ] TeratogenicOriginator
- [ ] Terramorph
- [ ] TetraSlug
- [ ] Thermadon
- [ ] Thunderbeast
- [x] Thunderox
- [ ] UnblinkingEye
- [ ] WaywardMobileAssembler
- [ ] Wildpawn/pod
- [ ] Windbeast

### CODE REVIEW

**Comment by Shabakur** [comment]
Thank you for contribution. It looks great! Only thing I am noticing is that for AA_ColossalAerofleet having them in the aerofleet racegenedef may cause some problems as everytime it tries to give genes it will only look at one of them. 
Some suggestions. Firstly try and add some genes which add metabolic efficiency, not a must, but without them the kids may get really bad metabolic efficiency frequently, I hope to have a solution for this in the future, but I haven't thought of one that I like. You could also scale back the chance for genes with large negative metabolci efficieny. Other suggestion, if you feel like it you could also include genes from other popular gene mods. Also I believe for aerofleet you should add blue gell production and the aerofleet hood genes, as they are aerogene based genes.

**Comment by WasmachenDennSachenSo** [comment]
> Only thing I am noticing is that for AA_ColossalAerofleet having them in the aerofleet racegenedef may cause some problems as everytime it tries to give genes it will only look at one of them.

Oh, good to know.

I thought that the child RaceGeneDef would be additive to the parent one. So the AeroFleet and the ColossalAeroFleet inherit AG_Detonation and rjw_genes_slime_genitals through the AeroFleet RaceGeneDef and the ColossalAeroFleet inherits rjw_genes_big_male_genitalia on top of that.

The canine childs should work right? Because PawnKindDefs have a higher priority than RaceGroups. 
So the genes in the canine child RaceGeneDefs are additive, right?

I currently don't have a testing workflow because i didn't find any useful debug tools inside rimworld to quickly inpregnate a woman and skip the pregnancy duration. Do you have a solid workflow for that?

> Some suggestions. Firstly try and add some genes which add metabolic efficiency, not a must, but without them the kids may get really bad metabolic efficiency frequently 

Good Point. I will try to keep that in mind.

> Other suggestion, if you feel like it you could also include genes from other popular gene mods

This is a point im unsure about. I feel like we shouldn't go overboard with this because people will need to install all of them. I don't know if they would want that. I also thought about creating a few of my own but creating duplicate genes to other mods seems to be bad aswell. Most of the genes i thought about already exist in one of the gene mods.

Thing is. These mods don't only add genes... they add factions and sometimes items aswell.

> Also I believe for aerofleet you should add blue gell production and the aerofleet hood genes, as they are aerogene based genes.

Yea the AeroFleet was the one I started out with for testing. I've added these genes in my local branch already :)

Thank you that you took the time to look this through! Greatly appreciated.

**Comment by Shabakur** [comment]
> I thought that the child RaceGeneDef would be additive to the parent one. So the AeroFleet and the ColossalAeroFleet inherit AG_Detonation and rjw_genes_slime_genitals through the AeroFleet RaceGeneDef and the ColossalAeroFleet inherits rjw_genes_big_male_genitalia on top of that.
Yes, but as the ColossalAerofleet is present in both racegenedefs it will select one of the two, so the chance of rjw_genes_big_male_genitalia is halved. I have made a pull request to
Vegapnk which adds a priority variable so you are able to decide which racegenedef should be used. 

> The canine childs should work right? Because PawnKindDefs have a higher priority than RaceGroups.
So the genes in the canine child RaceGeneDefs are additive, right?
Yes

> I currently don't have a testing workflow because i didn't find any useful debug tools inside rimworld to quickly inpregnate a woman and skip the pregnancy duration. Do you have a solid workflow for that?
If you use biotech pregnancy you should be able to see the child's genes immediately after birth. Do make sure to set in RJW pregnancy the DNA inheritance slides all to mother and to human to ensure human kid. There is also a debug action to increment time. Under rjw_debug you can get enable direct control to initiate the sex. 

You should also increase min vulnerability to rape or you can't have sex if your pawn's vulnerability is to high.

> This is a point im unsure about. I feel like we shouldn't go overboard with this because people will need to install all of them. I don't know if they would want that. I also thought about creating a few of my own but creating duplicate genes to other mods seems to be bad aswell. Most of the genes i thought about already exist in one of the gene mods.
I meant adding the genes inside the racegenedefs, you can add genes of mods that aren't active without problems. They just won't be used if the required mod isn't enabled.

**Comment by klassekatze** [comment]
> This is a point im unsure about. I feel like we shouldn't go overboard with this because people will need to install all of them. I don't know if they would want that. I also thought about creating a few of my own but creating duplicate genes to other mods seems to be bad aswell. Most of the genes i thought about already exist in one of the gene mods.
If you didn't know, you can make patches conditional on the presence of another mod using PatchOperationFindMod; so it can tack on those genes if they're available, but otherwise omit them without issue.

As for quick pregnancy - you can use IVF or whatnot and then use Character Editor to set the severity of the pregnancy to 100 immediately, which will skip to giving birth.

**Pull request closed without merging**
